import { Footer } from './(components)/Footer/Footer';
import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const handleGoToDashboard = () => {
    // Add the logic to navigate to the dashboard page here
    // You can use Next.js Router or any other navigation method you prefer.
  };

  return (
    <html lang="en" className=''>
      <body className={inter.className}>
        <Link
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded absolute top-1 right-4"
          href="/AdminPanel"
        >
          Go to Admin Panel
        </Link>
        {children}
      </body>
      <Footer />
    </html>
  );
}
